[project]
name = "pdu-floorplan-postprocess"
version = "0.1.0"
description = "Add a short description here"
authors = ["Bernat Ibáñez Martínez <personal@bibanez.xyz>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.4,<3.13"
python-lsp-server = ">=1.11.0,<1.12"
jupyterlab = ">=4.2.4,<4.3"

[pypi-dependencies]
python-sat = "*"
pypblib = "*"
